name: CI Workflow with Self-Hosted Runner

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the `main` branch

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner (your EC2 instance)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
